/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dbmanager.WordDatabaseManager;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Word;

/**
 *
 * @author Magnit
 */
public class addAndEditFrame extends javax.swing.JFrame {

    /**
     * Creates new form addAndEditFrame
     */
    Word word = null;

    public addAndEditFrame() {
        super("Add new word");
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("language.png")));
        buttonAddAndEdit.setText("Add");
        try {
            Image img = ImageIO.read(getClass().getResource("new.png"));
            buttonAddAndEdit.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(addAndEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public addAndEditFrame(String id) {
        super("Edit word");
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("language.png")));
        buttonAddAndEdit.setText("Save");
        try {
            Image image = ImageIO.read(getClass().getResource("save.png"));
            buttonAddAndEdit.setIcon(new ImageIcon(image));
        } catch (IOException ex) {
            Logger.getLogger(addAndEditFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        WordDatabaseManager wdm = new WordDatabaseManager();
        word = wdm.getWordById(Integer.parseInt(id));
        textFieldEn.setText(word.getWordEN());
        textFieldAz.setText(word.getWordAZ());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        textFieldEn = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        textFieldAz = new javax.swing.JTextField();
        buttonAddAndEdit = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label1.setText("English");

        textFieldEn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textFieldEn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldEnKeyTyped(evt);
            }
        });

        label2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        label2.setText("Azerbaijan");

        textFieldAz.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textFieldAz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldAzKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldAzKeyTyped(evt);
            }
        });

        buttonAddAndEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonAddAndEdit.setForeground(new java.awt.Color(0, 153, 204));
        buttonAddAndEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAndEditActionPerformed(evt);
            }
        });

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Magnit\\Downloads\\left-arrow.png")); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(buttonAddAndEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldAz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(textFieldEn, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldEn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(buttonAddAndEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldAz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        if (buttonAddAndEdit.getText().equals("Add")) {
            new MainFrame().setVisible(true);
        } else {
            new ConfigurationFrame().setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAddAndEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAndEditActionPerformed

        if (this.word == null) {
            Word word = new Word();
            word.setWordEN(textFieldEn.getText().trim().toLowerCase());
            word.setWordAZ(textFieldAz.getText().trim().toLowerCase());
            if (!textFieldEn.getText().trim().toLowerCase().isEmpty()
                    && !textFieldAz.getText().trim().toLowerCase().isEmpty()) {
                if (new WordDatabaseManager().addWord(word) == 1) {
                    JOptionPane.showMessageDialog(null, "The word is successfully added");
                } else {
                    JOptionPane.showMessageDialog(null, "The word is not added", "Error", JOptionPane.ERROR_MESSAGE);
                }
                textFieldEn.setText("");
                textFieldAz.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "The fields cannot be empty");
            }

        } else {
            word.setWordEN(textFieldEn.getText().trim().toLowerCase());
            word.setWordAZ(textFieldAz.getText().trim().toLowerCase());
            if (!textFieldEn.getText().trim().toLowerCase().isEmpty()
                    && !textFieldAz.getText().trim().toLowerCase().isEmpty()) {
                if (new WordDatabaseManager().updateWord(word) == 1) {
                    JOptionPane.showMessageDialog(null, "The word is edited");
                } else {
                    JOptionPane.showMessageDialog(null, "The word is not edited", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The fields cannot be empty");
            }
        }
    }//GEN-LAST:event_buttonAddAndEditActionPerformed

    private void textFieldAzKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAzKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            buttonAddAndEdit.doClick();
        }
    }//GEN-LAST:event_textFieldAzKeyPressed

    private void textFieldEnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldEnKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (Character.isWhitespace(c)) || c == KeyEvent.VK_BACK_SPACE
                || c == KeyEvent.VK_DELETE || c == '-')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textFieldEnKeyTyped

    private void textFieldAzKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAzKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || (Character.isWhitespace(c)) || c == KeyEvent.VK_BACK_SPACE
                || c == KeyEvent.VK_DELETE || c == '-')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textFieldAzKeyTyped

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAndEdit;
    private javax.swing.JButton buttonBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField textFieldAz;
    private javax.swing.JTextField textFieldEn;
    // End of variables declaration//GEN-END:variables

}
