/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dbmanager.WordDatabaseManager;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Word;
import com.sun.speech.freetts.*;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Magnit
 */
public class TranslateFrame extends javax.swing.JFrame {

    /**
     * Creates new form TranslateFrame
     */
    WordDatabaseManager wordDatabaseManager = new WordDatabaseManager();
    DefaultListModel<String> listModel = new DefaultListModel<>();
    List<Word> list = new ArrayList<>();

    public TranslateFrame() {
        super("Translate");
        initComponents();
        list = wordDatabaseManager.allWords();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("language.png")));
        textArea1.setLineWrap(true);
        textArea2.setLineWrap(true);
        textArea2.setEditable(false);
        buttonSpeaker2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        languageChanger = new javax.swing.JButton();
        buttonTranslate = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        buttonBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlist = new javax.swing.JList<>();
        buttonSpeaker1 = new javax.swing.JButton();
        buttonSpeaker2 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 204));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("English");

        label2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 204));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Azerbaijani");

        languageChanger.setBackground(new java.awt.Color(255, 255, 255));
        languageChanger.setIcon(new javax.swing.ImageIcon("C:\\Users\\Magnit\\Downloads\\revert-hand-drawn-arrows (2).png")); // NOI18N
        languageChanger.setMnemonic('A');
        languageChanger.setToolTipText("Swap languages");
        languageChanger.setBorder(null);
        languageChanger.setBorderPainted(false);
        languageChanger.setContentAreaFilled(false);
        languageChanger.setFocusPainted(false);
        languageChanger.setMargin(new java.awt.Insets(0, 0, 0, 0));
        languageChanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageChangerActionPerformed(evt);
            }
        });

        buttonTranslate.setEnabled(false);
        buttonTranslate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTranslate.setForeground(new java.awt.Color(0, 0, 204));
        buttonTranslate.setText("Translate");
        buttonTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTranslateActionPerformed(evt);
            }
        });

        checkBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkBox.setText("Use button");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        textArea1.setColumns(20);
        textArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textArea1.setRows(5);
        textArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(textArea1);

        textArea2.setColumns(20);
        textArea2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textArea2.setRows(5);
        jScrollPane2.setViewportView(textArea2);

        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Magnit\\Downloads\\left-arrow.png")); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jlist.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suggested words", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N
        jlist.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jlist);

        buttonSpeaker1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Magnit\\Downloads\\speaker-filled-audio-tool (1).png")); // NOI18N
        buttonSpeaker1.setToolTipText("Listen");
        buttonSpeaker1.setBorderPainted(false);
        buttonSpeaker1.setContentAreaFilled(false);
        buttonSpeaker1.setFocusPainted(false);
        buttonSpeaker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpeaker1ActionPerformed(evt);
            }
        });

        buttonSpeaker2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Magnit\\Downloads\\speaker-filled-audio-tool (1).png")); // NOI18N
        buttonSpeaker2.setToolTipText("Listen");
        buttonSpeaker2.setBorderPainted(false);
        buttonSpeaker2.setContentAreaFilled(false);
        buttonSpeaker2.setFocusPainted(false);
        buttonSpeaker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSpeaker2ActionPerformed(evt);
            }
        });

        clearButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Magnit\\Downloads\\delete (2).png")); // NOI18N
        clearButton.setToolTipText("Clear text");
        clearButton.setBorderPainted(false);
        clearButton.setContentAreaFilled(false);
        clearButton.setFocusPainted(false);
        clearButton.setOpaque(true);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(buttonBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(languageChanger, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSpeaker1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSpeaker2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(languageChanger)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSpeaker1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonSpeaker2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTranslate)
                            .addComponent(checkBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    boolean flag = true;   // enable and disable translate button
    boolean flag2 = true;  // it will check i will use keyrelease or not

    private void languageChangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageChangerActionPerformed
        // TODO add your handling code here:
        if (flag == false) {
            label1.setText("English");
            label2.setText("Azerbaijani");
            buttonSpeaker1.setEnabled(true);
            buttonSpeaker2.setEnabled(false);
            flag = true;
        } else {
            label1.setText("Azerbaijani");
            label2.setText("English");
            buttonSpeaker2.setEnabled(true);
            buttonSpeaker1.setEnabled(false);
            flag = false;
        }
        String temp = textArea1.getText();
        textArea1.setText("");
        textArea1.setText(textArea2.getText());
        textArea2.setText(temp);
        listModel.removeAllElements();
    }//GEN-LAST:event_languageChangerActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        // TODO add your handling code here:
        if (checkBox.isSelected()) {
            buttonTranslate.setEnabled(true);
            flag2 = false;
            listModel.removeAllElements();
            jlist.setModel(listModel);
            jlist.setVisible(false);
        } else {
            buttonTranslate.setEnabled(false);
            jlist.setVisible(true);
            flag2 = true;
            searchInWordList();
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    private void textArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textArea1KeyReleased
        // TODO add your handling code here:
        textArea2.setText("");
        if (flag2 == true) {
            searchInWordList();
        }
    }//GEN-LAST:event_textArea1KeyReleased

    private void buttonTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTranslateActionPerformed

        if (label1.getText().equals("Azerbaijani")) {
            list.stream().filter((w) -> (w.getWordAZ().toLowerCase().equalsIgnoreCase(textArea1.getText().trim().toLowerCase()))).forEachOrdered((w) -> {
                if (!textArea2.getText().contains(w.getWordEN().toLowerCase())) {
                    textArea2.append(w.getWordEN().toLowerCase() + "\n");
                }
            });
            if (textArea1.getText().equals("")) {
                textArea2.setText("");
            }
        } else {
            list.stream().filter((w) -> (w.getWordEN().toLowerCase().equalsIgnoreCase(textArea1.getText().trim().toLowerCase()))).forEachOrdered((w) -> {
                if (!textArea2.getText().contains(w.getWordAZ().trim().toLowerCase())) {
                    textArea2.append(w.getWordAZ().toLowerCase() + "\n");
                }
            });
            if (textArea1.getText().equals("")) {
                textArea2.setText("");
            }
        }
    }//GEN-LAST:event_buttonTranslateActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void jlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistMouseClicked
        // TODO add your handling code here:
        textArea2.setText("");
        String value = jlist.getSelectedValue();
        textArea1.setText(value);
        if (label1.getText().equals("English")) {
            ArrayList<Word> traList = new ArrayList<>();
            traList = wordDatabaseManager.getWord_AZ(value);
            for (Word word : traList) {
                textArea2.append(word.getWordAZ() + "\n");
            }
        } else if (label1.getText().equals("Azerbaijani")) {
            ArrayList<Word> traList = new ArrayList<>();
            traList = wordDatabaseManager.getWord_EN(value);
            for (Word word : traList) {
                textArea2.append(word.getWordEN() + "\n");
            }
        }
    }//GEN-LAST:event_jlistMouseClicked
    private static final String VOICENAME = "kevin16";

    private void speaker(JTextArea textArea) {
        VoiceManager voiceManager = VoiceManager.getInstance();
        Voice voice = voiceManager.getVoice(VOICENAME);
        voice.allocate();
        try {
            voice.speak(textArea.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "The problem occured");
        }
    }
    private void buttonSpeaker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpeaker1ActionPerformed
        // TODO add your handling code here:
        speaker(textArea1);
    }//GEN-LAST:event_buttonSpeaker1ActionPerformed

    private void buttonSpeaker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSpeaker2ActionPerformed
        // TODO add your handling code here:
        speaker(textArea2);
    }//GEN-LAST:event_buttonSpeaker2ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        textArea1.setText("");
        textArea2.setText("");
        listModel.removeAllElements();
        jlist.setModel(listModel);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchInWordList() {
        // Word word = list.stream().filter(w -> textField1.getText().equals(w.getWordAZ())).findAny().orElse(null);
        listModel.removeAllElements();
        jlist.setModel(listModel);
        if (label1.getText().equals("Azerbaijani")) {
            list.stream().filter((w) -> (w.getWordAZ().toLowerCase().startsWith(textArea1.getText().trim().toLowerCase()))).forEachOrdered((w) -> {
                if (!listModel.contains(w.getWordAZ().toLowerCase())) {
                    listModel.addElement(w.getWordAZ().toLowerCase());
                }
                jlist.setModel(listModel);
            });

            if (textArea1.getText().equals("")) {
                textArea2.setText("");
                listModel.removeAllElements();
            }
        } else {
            list.stream().filter((w) -> (w.getWordEN().toLowerCase().startsWith(textArea1.getText().trim().toLowerCase()))).forEachOrdered((w) -> {
                if (!listModel.contains(w.getWordEN().toLowerCase())) {
                    listModel.addElement(w.getWordEN().toLowerCase());
                }
                jlist.setModel(listModel);
            });
            if (textArea1.getText().equals("")) {
                textArea2.setText("");
                listModel.removeAllElements();
            }
        }
    }

//    private void languageChanger() {
//        InputContext context = InputContext.getInstance();
//        Locale locale = context.getLocale();
//
//        Locale azerbaijan = new Locale("az", "AZ");
//        Locale english = new Locale("en", "US");
//
//        if (context.selectInputMethod(english)) {
//            context.selectInputMethod(azerbaijan);
//
//        } else {
//            context.selectInputMethod(english);
//        }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonSpeaker1;
    private javax.swing.JButton buttonSpeaker2;
    private javax.swing.JButton buttonTranslate;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jlist;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton languageChanger;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
